---
- hosts: local
  user: centos
  become: yes
  tasks:
    - name: installation of docker
      shell: |

              yum install -y yum-utils device-mapper-persistent-data lvm2
              yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
              yum-config-manager --enable docker-ce-edge
              yum-config-manager --enable docker-ce-test
              yum install docker-ce
              systemctl start docker
              systemctl enable docker
              systemctl status docker
              docker --version
              docker images
      register: result
    - debug: var=result 
